{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-index.fullname" . }}-postgresql
  namespace: postgresql
  labels:
    {{- include "data-index.labels" . | nindent 4 }}
    app: postgresql
type: Opaque
stringData:
  postgres-username: {{ .Values.postgresql.username | quote }}
  postgres-password: {{ .Values.postgresql.password | quote }}
{{- end }}
