{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) -}}
---
# Secret in postgresql namespace (for PostgreSQL pod)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-index.fullname" . }}-postgresql
  namespace: postgresql
  labels:
    {{- include "data-index.labels" . | nindent 4 }}
    app: postgresql
type: Opaque
stringData:
  postgres-username: {{ .Values.postgresql.username | quote }}
  postgres-password: {{ .Values.postgresql.password | quote }}

---
# Secret in default namespace (for data-index-service and data-index-ingestion pods)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-index.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-index.labels" . | nindent 4 }}
    app: postgresql
type: Opaque
stringData:
  postgres-username: {{ .Values.postgresql.username | quote }}
  postgres-password: {{ .Values.postgresql.password | quote }}
{{- end }}
