####
# This Dockerfile is used to build a JVM container that runs the Quarkus application in JVM mode
####
FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:1.23

ENV LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

# Create log directory for Quarkus Flow events (as root)
USER root
RUN mkdir -p /var/log/quarkus-flow && chown -R 185:185 /var/log/quarkus-flow

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
